import { ConnectionContainer } from "@/containers/connectionPage";
import LayoutComponent from "@/layouts/LayoutComponent";
import type { NextPage } from "next";
import Head from "next/head";

const ConnectionPage: NextPage = () => {
  return (
    <>
    <Head>
      <title>Connection</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <LayoutComponent>
    
          <ConnectionContainer/>
      </LayoutComponent>
  </>
  )
}

export default ConnectionPage